{
 "title": "Inventory",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total of Structures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spacetraderinventory_structurecount"
    }
   ]
  },
  {
   "title": "Total of Ships",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spacetraderinventory_shipcount" }
   ]
  },
  {
   "title": "Rank Position",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spacetraderinventory_userrank" }
   ]
  },
  {
   "title": "Credits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "spacetraderinventory_credits" }
   ]
  },
  {
   "title": "Ship List (Broken)",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "spacetraderinventory_shipload", "legendFormat": "__auto" }
   ]
  }
 ]
}